sudo: required 
dist: trusty 
language: generic 
env:
  - ROS_DISTRO="indigo"
install:
  - git clone --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci  
script: 
  - .industrial_ci/travis.sh
